-- Seed file: runs automatically after migrations on `supabase db reset`.
-- Reference data only. Tenancy seed is in Task 8.

-- variables
INSERT INTO variables (code, name, category, direction, is_quantitative, description) VALUES
  ('dcpi_5_adj', 'Inflation 5 year average', 'Economic'::variable_category, 'higher_worse'::direction_code, true, 'Average CPI % change over 5 years.'),
  ('nom_rir_vol', 'Nominal Interest Rate Volatility', 'Economic'::variable_category, 'higher_worse'::direction_code, true, 'Volatility of nominal interest rates.'),
  ('gdp_capita', 'GDP per Capita', 'Economic'::variable_category, 'higher_better'::direction_code, true, 'GDP per head (US$).'),
  ('growth_vol', 'Growth Volatility', 'Economic'::variable_category, 'higher_worse'::direction_code, true, 'Stdev of Real GDP % change over 5 years.'),
  ('macro_var', 'Macroeconomic', 'Economic'::variable_category, 'higher_better'::direction_code, false, 'Qualitative macroeconomic stability score.'),
  ('atf', 'Access to Finance', 'Currency'::variable_category, 'higher_better'::direction_code, false, 'Qualitative access-to-finance score.'),
  ('dt', 'Debt Trend', 'Currency'::variable_category, 'higher_worse'::direction_code, true, '3-year trend in foreign debt to GDP.'),
  ('fdg_3yr', 'Foreign Debt to GDP 3 year average', 'Currency'::variable_category, 'higher_worse'::direction_code, true, 'Average foreign debt / GDP over 3 years.'),
  ('cof', 'Cost of Funds', 'Finance'::variable_category, 'higher_worse'::direction_code, true, 'Money market interest rate (%).'),
  ('pr', 'Political Risk Environment', 'Political'::variable_category, 'higher_better'::direction_code, false, 'Qualitative political risk score.'),
  ('rol', 'Rule of Law', 'Business Risk'::variable_category, 'higher_better'::direction_code, false, 'World Governance Indicator: Rule of Law.'),
  ('db', 'Doing Business', 'Business Risk'::variable_category, 'higher_better'::direction_code, false, 'World Bank Doing Business qualitative score.'),
  ('sr', 'Security Risk', 'Risk'::variable_category, 'higher_better'::direction_code, false, 'Global Insights security risk score.'),
  ('debt_service_ratio', 'Debt Service Ratio 1 year', 'Currency'::variable_category, 'higher_worse'::direction_code, true, 'Debt service due as % of exports + remittances.')
ON CONFLICT (code) DO NOTHING;

-- countries
INSERT INTO countries (iso3, name, region) VALUES
  ('AFG', 'AFGHANISTAN', 'EMERGING_NON_AFRICA'),
  ('ALB', 'ALBANIA', 'EMERGING_NON_AFRICA'),
  ('DZA', 'ALGERIA', 'AFRICA'),
  ('AGO', 'ANGOLA', 'AFRICA'),
  ('ATG', 'ANTIGUA AND BARBUDA', 'EMERGING_NON_AFRICA'),
  ('ARG', 'ARGENTINA', 'EMERGING_NON_AFRICA'),
  ('ARM', 'ARMENIA', 'EMERGING_NON_AFRICA'),
  ('AUS', 'AUSTRALIA', 'DEVELOPED'),
  ('AUT', 'AUSTRIA', 'DEVELOPED'),
  ('AZE', 'AZERBAIJAN', 'EMERGING_NON_AFRICA'),
  ('BHS', 'BAHAMAS', 'EMERGING_NON_AFRICA'),
  ('BHR', 'BAHRAIN', 'EMERGING_NON_AFRICA'),
  ('BGD', 'BANGLADESH', 'EMERGING_NON_AFRICA'),
  ('BRB', 'BARBADOS', 'DEVELOPED'),
  ('BLR', 'BELARUS', 'EMERGING_NON_AFRICA'),
  ('BEL', 'BELGIUM', 'DEVELOPED'),
  ('BLZ', 'BELIZE', 'EMERGING_NON_AFRICA'),
  ('BMU', 'BERMUDA', 'DEVELOPED'),
  ('BOL', 'BOLIVIA, PLURINATIONAL STATE OF', 'EMERGING_NON_AFRICA'),
  ('BIH', 'BOSNIA AND HERZEGOVINA', 'EMERGING_NON_AFRICA'),
  ('BWA', 'BOTSWANA', 'AFRICA'),
  ('BRA', 'BRAZIL', 'EMERGING_NON_AFRICA'),
  ('BGR', 'BULGARIA', 'EMERGING_NON_AFRICA'),
  ('BFA', 'BURKINA FASO', 'AFRICA'),
  ('KHM', 'CAMBODIA', 'EMERGING_NON_AFRICA'),
  ('CMR', 'CAMEROON', 'AFRICA'),
  ('CAN', 'CANADA', 'DEVELOPED'),
  ('CYM', 'CAYMAN ISLANDS', 'EMERGING_NON_AFRICA'),
  ('CAF', 'CENTRAL AFRICAN REPUBLIC', 'AFRICA'),
  ('CHL', 'CHILE', 'EMERGING_NON_AFRICA'),
  ('CHN', 'CHINA', 'EMERGING_NON_AFRICA'),
  ('COL', 'COLOMBIA', 'EMERGING_NON_AFRICA'),
  ('COG', 'CONGO', 'AFRICA'),
  ('COD', 'CONGO, THE DEMOCRATIC REP OF THE', 'AFRICA'),
  ('CRI', 'COSTA-RICA', 'EMERGING_NON_AFRICA'),
  ('CIV', 'COTE D''IVOIRE', 'AFRICA'),
  ('HRV', 'CROATIA', 'EMERGING_NON_AFRICA'),
  ('CUB', 'CUBA', 'EMERGING_NON_AFRICA'),
  ('CYP', 'CYPRUS', 'DEVELOPED'),
  ('CZE', 'CZECH REPUBLIC', 'EMERGING_NON_AFRICA'),
  ('DNK', 'DENMARK', 'DEVELOPED'),
  ('DOM', 'DOMINICAN REPUBLIC', 'EMERGING_NON_AFRICA'),
  ('ECU', 'ECUADOR', 'EMERGING_NON_AFRICA'),
  ('EGY', 'EGYPT', 'EMERGING_NON_AFRICA'),
  ('SLV', 'EL SALVADOR', 'EMERGING_NON_AFRICA'),
  ('EST', 'ESTONIA', 'EMERGING_NON_AFRICA'),
  ('ETH', 'ETHIOPIA', 'AFRICA'),
  ('FJI', 'FIJI', 'EMERGING_NON_AFRICA'),
  ('FIN', 'FINLAND', 'DEVELOPED'),
  ('FRA', 'FRANCE', 'DEVELOPED'),
  ('GAB', 'GABON', 'AFRICA'),
  ('GEO', 'GEORGIA', 'EMERGING_NON_AFRICA'),
  ('DEU', 'GERMANY', 'DEVELOPED'),
  ('GHA', 'GHANA', 'AFRICA'),
  ('GIB', 'GIBRALTAR', 'DEVELOPED'),
  ('GRC', 'GREECE', 'DEVELOPED'),
  ('GTM', 'GUATEMALA', 'EMERGING_NON_AFRICA'),
  ('GGY', 'GUERNSEY', 'DEVELOPED'),
  ('HND', 'HONDURAS', 'EMERGING_NON_AFRICA'),
  ('HKG', 'HONG KONG', 'DEVELOPED'),
  ('HUN', 'HUNGARY', 'EMERGING_NON_AFRICA'),
  ('ISL', 'ICELAND', 'DEVELOPED'),
  ('IND', 'INDIA', 'EMERGING_NON_AFRICA'),
  ('IDN', 'INDONESIA', 'EMERGING_NON_AFRICA'),
  ('IRN', 'IRAN, ISLAMIC REPUBLIC OF', 'EMERGING_NON_AFRICA'),
  ('IRQ', 'IRAQ', 'EMERGING_NON_AFRICA'),
  ('IRL', 'IRELAND', 'DEVELOPED'),
  ('IMN', 'ISLE OF MAN', 'DEVELOPED'),
  ('ISR', 'ISRAEL', 'EMERGING_NON_AFRICA'),
  ('ITA', 'ITALY', 'DEVELOPED'),
  ('JAM', 'JAMAICA', 'EMERGING_NON_AFRICA'),
  ('JPN', 'JAPAN', 'DEVELOPED'),
  ('JEY', 'JERSEY', 'DEVELOPED'),
  ('JOR', 'JORDAN', 'EMERGING_NON_AFRICA'),
  ('KAZ', 'KAZAKHSTAN', 'EMERGING_NON_AFRICA'),
  ('KEN', 'KENYA', 'AFRICA'),
  ('PRK', 'KOREA, DEMOCRATIC PEOPLE''S REP OF', 'EMERGING_NON_AFRICA'),
  ('KOR', 'KOREA, REPUBLIC OF', 'EMERGING_NON_AFRICA'),
  ('KWT', 'KUWAIT', 'EMERGING_NON_AFRICA'),
  ('KGZ', 'KYRGYZSTAN', 'EMERGING_NON_AFRICA'),
  ('LVA', 'LATVIA', 'EMERGING_NON_AFRICA'),
  ('LBN', 'LEBANON', 'EMERGING_NON_AFRICA'),
  ('LSO', 'LESOTHO', 'EMERGING_NON_AFRICA'),
  ('LBY', 'LIBYAN ARAB JAMAHIRIYA', 'AFRICA'),
  ('LIE', 'LIECHTENSTEIN', 'DEVELOPED'),
  ('LTU', 'LITHUANIA', 'EMERGING_NON_AFRICA'),
  ('LUX', 'LUXEMBOURG', 'DEVELOPED'),
  ('MAC', 'MACAO', 'EMERGING_NON_AFRICA'),
  ('MKD', 'MACEDONIA, THE FORMER YUGOSLAV REP', 'EMERGING_NON_AFRICA'),
  ('MDG', 'MADAGASCAR', 'AFRICA'),
  ('MWI', 'MALAWI', 'AFRICA'),
  ('MYS', 'MALAYSIA', 'EMERGING_NON_AFRICA'),
  ('MLI', 'MALI', 'AFRICA'),
  ('MLT', 'MALTA', 'DEVELOPED'),
  ('MUS', 'MAURITIUS', 'AFRICA'),
  ('MEX', 'MEXICO', 'EMERGING_NON_AFRICA'),
  ('MCO', 'MONACO', 'DEVELOPED'),
  ('MNG', 'MONGOLIA', 'EMERGING_NON_AFRICA'),
  ('MAR', 'MOROCCO', 'AFRICA'),
  ('MOZ', 'MOZAMBIQUE', 'AFRICA'),
  ('NAM', 'NAMIBIA', 'EMERGING_NON_AFRICA'),
  ('NLD', 'NETHERLANDS', 'DEVELOPED'),
  ('ANT', 'NETHERLANDS ANTILLES', 'EMERGING_NON_AFRICA'),
  ('NZL', 'NEW ZEALAND', 'DEVELOPED'),
  ('NIC', 'NICARAGUA', 'EMERGING_NON_AFRICA'),
  ('NGA', 'NIGERIA', 'AFRICA'),
  ('NOR', 'NORWAY', 'DEVELOPED'),
  ('OMN', 'OMAN', 'EMERGING_NON_AFRICA'),
  ('PAK', 'PAKISTAN', 'EMERGING_NON_AFRICA'),
  ('PSE', 'PALESTINIAN TERRITORY, OCCUPIED', 'EMERGING_NON_AFRICA'),
  ('PAN', 'PANAMA', 'EMERGING_NON_AFRICA'),
  ('PNG', 'PAPUA NEW GUINEA', 'EMERGING_NON_AFRICA'),
  ('PER', 'PERU', 'EMERGING_NON_AFRICA'),
  ('PHL', 'PHILIPPINES', 'EMERGING_NON_AFRICA'),
  ('POL', 'POLAND', 'EMERGING_NON_AFRICA'),
  ('PRT', 'PORTUGAL', 'DEVELOPED'),
  ('PRI', 'PUERTO RICO', 'EMERGING_NON_AFRICA'),
  ('QAT', 'QATAR', 'EMERGING_NON_AFRICA'),
  ('REU', 'REUNION', 'DEVELOPED'),
  ('ROU', 'ROMANIA', 'EMERGING_NON_AFRICA'),
  ('RUS', 'RUSSIAN FEDERATION', 'EMERGING_NON_AFRICA'),
  ('RWA', 'RWANDA', 'AFRICA'),
  ('SAU', 'SAUDI ARABIA', 'EMERGING_NON_AFRICA'),
  ('SEN', 'SENEGAL', 'AFRICA'),
  ('SRB', 'SERBIA', 'EMERGING_NON_AFRICA'),
  ('SYC', 'SEYCHELLES', 'AFRICA'),
  ('SLE', 'SIERRA LEONE', 'AFRICA'),
  ('SGP', 'SINGAPORE', 'DEVELOPED'),
  ('SVK', 'SLOVAKIA', 'EMERGING_NON_AFRICA'),
  ('SVN', 'SLOVENIA', 'EMERGING_NON_AFRICA'),
  ('ZAF', 'SOUTH AFRICA', 'AFRICA'),
  ('ESP', 'SPAIN', 'DEVELOPED'),
  ('LKA', 'SRI LANKA', 'EMERGING_NON_AFRICA'),
  ('SDN', 'SUDAN', 'AFRICA'),
  ('SWZ', 'SWAZILAND', 'EMERGING_NON_AFRICA'),
  ('SWE', 'SWEDEN', 'DEVELOPED'),
  ('CHE', 'SWITZERLAND', 'DEVELOPED'),
  ('TWN', 'TAIWAN, PROVINCE OF CHINA', 'DEVELOPED'),
  ('TJK', 'TAJIKISTAN', 'EMERGING_NON_AFRICA'),
  ('TZA', 'TANZANIA, UNITED REPUBLIC OF', 'AFRICA'),
  ('THA', 'THAILAND', 'EMERGING_NON_AFRICA'),
  ('TGO', 'TOGO', 'AFRICA'),
  ('TTO', 'TRINIDAD AND TOBAGO', 'EMERGING_NON_AFRICA'),
  ('TUN', 'TUNISIA', 'AFRICA'),
  ('TUR', 'TURKEY', 'EMERGING_NON_AFRICA'),
  ('UGA', 'UGANDA', 'AFRICA'),
  ('UKR', 'UKRAINE', 'EMERGING_NON_AFRICA'),
  ('ARE', 'UNITED ARAB EMIRATES', 'EMERGING_NON_AFRICA'),
  ('GBR', 'UNITED KINGDOM', 'DEVELOPED'),
  ('USA', 'UNITED STATES', 'DEVELOPED'),
  ('URY', 'URUGUAY', 'EMERGING_NON_AFRICA'),
  ('UZB', 'UZBEKISTAN', 'EMERGING_NON_AFRICA'),
  ('VEN', 'VENEZUELA, BOLIVARIAN REPUBLIC OF', 'EMERGING_NON_AFRICA'),
  ('VNM', 'VIETNAM', 'EMERGING_NON_AFRICA'),
  ('VGB', 'VIRGIN ISLANDS (BRITISH)', 'DEVELOPED'),
  ('VIR', 'VIRGIN ISLANDS (U.S.)', 'DEVELOPED'),
  ('YEM', 'YEMEN', 'EMERGING_NON_AFRICA'),
  ('ZMB', 'ZAMBIA', 'AFRICA'),
  ('ZWE', 'ZIMBABWE', 'AFRICA')
ON CONFLICT (iso3) DO NOTHING;

-- country_segments
INSERT INTO country_segments (iso3, as_of_year, hdi_value, segment) VALUES
  ('AFG', 2011, 0.45, 'LOW'::segment_code),
  ('ALB', 2011, 0.75, 'HIGH'::segment_code),
  ('DZA', 2011, 0.6, 'NODATA'::segment_code),
  ('AGO', 2011, 0.45, 'LOW'::segment_code),
  ('ATG', 2011, 0.75, 'NODATA'::segment_code),
  ('ARG', 2011, 0.6, 'HIGH'::segment_code),
  ('ARM', 2011, 0.75, 'HIGH'::segment_code),
  ('AUS', 2011, 0.9, 'HIGH'::segment_code),
  ('AUT', 2011, 0.9, 'HIGH'::segment_code),
  ('AZE', 2011, 0.6, 'HIGH'::segment_code),
  ('BHS', 2011, 0.75, 'NODATA'::segment_code),
  ('BHR', 2011, 0.75, 'HIGH'::segment_code),
  ('BGD', 2011, 0.45, 'LOW'::segment_code),
  ('BRB', 2011, 0.9, 'NODATA'::segment_code),
  ('BLR', 2011, 0.75, 'HIGH'::segment_code),
  ('BEL', 2011, 0.9, 'HIGH'::segment_code),
  ('BLZ', 2011, 0.75, 'NODATA'::segment_code),
  ('BMU', 2011, 0.9, 'NODATA'::segment_code),
  ('BOL', 2011, 0.45, 'LOW'::segment_code),
  ('BIH', 2011, 0.75, 'HIGH'::segment_code),
  ('BWA', 2011, 0.6, 'LOW'::segment_code),
  ('BRA', 2011, 0.75, 'HIGH'::segment_code),
  ('BGR', 2011, 0.75, 'HIGH'::segment_code),
  ('BFA', 2011, 0.45, 'LOW'::segment_code),
  ('KHM', 2011, 0.6, 'LOW'::segment_code),
  ('CMR', 2011, 0.45, 'LOW'::segment_code),
  ('CAN', 2011, 0.9, 'HIGH'::segment_code),
  ('CYM', 2011, 0.9, 'NODATA'::segment_code),
  ('CAF', 2011, 0.45, 'NODATA'::segment_code),
  ('CHL', 2011, 0.9, 'HIGH'::segment_code),
  ('CHN', 2011, 0.6, 'LOW'::segment_code),
  ('COL', 2011, 0.75, 'HIGH'::segment_code),
  ('COG', 2011, 0.45, 'LOW'::segment_code),
  ('COD', 2011, 0.45, 'LOW'::segment_code),
  ('CRI', 2011, 0.75, 'HIGH'::segment_code),
  ('CIV', 2011, 0.6, 'LOW'::segment_code),
  ('HRV', 2011, 0.75, 'HIGH'::segment_code),
  ('CUB', 2011, 0.75, 'HIGH'::segment_code),
  ('CYP', 2011, 0.9, 'HIGH'::segment_code),
  ('CZE', 2011, 0.9, 'HIGH'::segment_code),
  ('DNK', 2011, 0.9, 'HIGH'::segment_code),
  ('DOM', 2011, 0.6, 'LOW'::segment_code),
  ('ECU', 2011, 0.6, 'HIGH'::segment_code),
  ('EGY', 2011, 0.6, 'LOW'::segment_code),
  ('SLV', 2011, 0.6, 'LOW'::segment_code),
  ('EST', 2011, 0.9, 'HIGH'::segment_code),
  ('ETH', 2011, 0.45, 'LOW'::segment_code),
  ('FJI', 2011, 0.6, 'LOW'::segment_code),
  ('FIN', 2011, 0.9, 'HIGH'::segment_code),
  ('FRA', 2011, 0.9, 'HIGH'::segment_code),
  ('GAB', 2011, 0.6, 'NODATA'::segment_code),
  ('GEO', 2011, 0.75, 'HIGH'::segment_code),
  ('DEU', 2011, 0.9, 'HIGH'::segment_code),
  ('GHA', 2011, 0.6, 'LOW'::segment_code),
  ('GIB', 2011, 0.9, 'NODATA'::segment_code),
  ('GRC', 2011, 0.75, 'HIGH'::segment_code),
  ('GTM', 2011, 0.6, 'LOW'::segment_code),
  ('GGY', 2011, 0.9, 'NODATA'::segment_code),
  ('HND', 2011, 0.6, 'LOW'::segment_code),
  ('HKG', 2011, 0.9, 'HIGH'::segment_code),
  ('HUN', 2011, 0.75, 'HIGH'::segment_code),
  ('ISL', 2011, 0.9, 'HIGH'::segment_code),
  ('IND', 2011, 0.6, 'LOW'::segment_code),
  ('IDN', 2011, 0.6, 'LOW'::segment_code),
  ('IRN', 2011, 0.75, 'NODATA'::segment_code),
  ('IRQ', 2011, 0.45, 'LOW'::segment_code),
  ('IRL', 2011, 0.9, 'HIGH'::segment_code),
  ('IMN', 2011, 0.9, 'NODATA'::segment_code),
  ('ISR', 2011, 0.75, 'HIGH'::segment_code),
  ('ITA', 2011, 0.9, 'HIGH'::segment_code),
  ('JAM', 2011, 0.6, 'HIGH'::segment_code),
  ('JPN', 2011, 0.9, 'HIGH'::segment_code),
  ('JEY', 2011, 0.9, 'NODATA'::segment_code),
  ('JOR', 2011, 0.6, 'LOW'::segment_code),
  ('KAZ', 2011, 0.75, 'HIGH'::segment_code),
  ('KEN', 2011, 0.6, 'LOW'::segment_code),
  ('PRK', 2011, 0.45, 'NODATA'::segment_code),
  ('KOR', 2011, 0.9, 'HIGH'::segment_code),
  ('KWT', 2011, 0.75, 'HIGH'::segment_code),
  ('KGZ', 2011, 0.45, 'NODATA'::segment_code),
  ('LVA', 2011, 0.9, 'HIGH'::segment_code),
  ('LBN', 2011, 0.6, 'HIGH'::segment_code),
  ('LSO', 2011, 0.6, 'LOW'::segment_code),
  ('LBY', 2011, 0.6, 'HIGH'::segment_code),
  ('LIE', 2011, 0.9, 'NODATA'::segment_code),
  ('LTU', 2011, 0.75, 'HIGH'::segment_code),
  ('LUX', 2011, 0.9, 'HIGH'::segment_code),
  ('MAC', 2011, 0.75, 'HIGH'::segment_code),
  ('MKD', 2011, 0.75, 'HIGH'::segment_code),
  ('MDG', 2011, 0.45, 'NODATA'::segment_code),
  ('MWI', 2011, 0.45, 'LOW'::segment_code),
  ('MYS', 2011, 0.75, 'HIGH'::segment_code),
  ('MLI', 2011, 0.45, 'LOW'::segment_code),
  ('MLT', 2011, 0.9, 'NODATA'::segment_code),
  ('MUS', 2011, 0.75, 'HIGH'::segment_code),
  ('MEX', 2011, 0.75, 'HIGH'::segment_code),
  ('MCO', 2011, 0.9, 'NODATA'::segment_code),
  ('MNG', 2011, 0.6, 'LOW'::segment_code),
  ('MAR', 2011, 0.6, 'LOW'::segment_code),
  ('MOZ', 2011, 0.45, 'LOW'::segment_code),
  ('NAM', 2011, 0.6, 'LOW'::segment_code),
  ('NLD', 2011, 0.9, 'HIGH'::segment_code),
  ('ANT', 2011, 0.9, 'NODATA'::segment_code),
  ('NZL', 2011, 0.9, 'HIGH'::segment_code),
  ('NIC', 2011, 0.6, 'NODATA'::segment_code),
  ('NGA', 2011, 0.6, 'LOW'::segment_code),
  ('NOR', 2011, 0.9, 'HIGH'::segment_code),
  ('OMN', 2011, 0.75, 'HIGH'::segment_code),
  ('PAK', 2011, 0.45, 'LOW'::segment_code),
  ('PSE', 2011, 0.6, 'NODATA'::segment_code),
  ('PAN', 2011, 0.75, 'HIGH'::segment_code),
  ('PNG', 2011, 0.45, 'LOW'::segment_code),
  ('PER', 2011, 0.75, 'HIGH'::segment_code),
  ('PHL', 2011, 0.6, 'LOW'::segment_code),
  ('POL', 2011, 0.9, 'HIGH'::segment_code),
  ('PRT', 2011, 0.9, 'HIGH'::segment_code),
  ('PRI', 2011, 0.9, 'NODATA'::segment_code),
  ('QAT', 2011, 0.9, 'HIGH'::segment_code),
  ('REU', 2011, 0.75, 'NODATA'::segment_code),
  ('ROU', 2011, 0.75, 'HIGH'::segment_code),
  ('RUS', 2011, 0.75, 'HIGH'::segment_code),
  ('RWA', 2011, 0.45, 'NODATA'::segment_code),
  ('SAU', 2011, 0.6, 'HIGH'::segment_code),
  ('SEN', 2011, 0.6, 'LOW'::segment_code),
  ('SRB', 2011, 0.75, 'HIGH'::segment_code),
  ('SYC', 2011, 0.75, 'HIGH'::segment_code),
  ('SLE', 2011, 0.45, 'LOW'::segment_code),
  ('SGP', 2011, 0.9, 'HIGH'::segment_code),
  ('SVK', 2011, 0.9, 'HIGH'::segment_code),
  ('SVN', 2011, 0.9, 'HIGH'::segment_code),
  ('ZAF', 2011, 0.6, 'LOW'::segment_code),
  ('ESP', 2011, 0.9, 'HIGH'::segment_code),
  ('LKA', 2011, 0.6, 'LOW'::segment_code),
  ('SDN', 2011, 0.45, 'NODATA'::segment_code),
  ('SWZ', 2011, 0.6, 'LOW'::segment_code),
  ('SWE', 2011, 0.9, 'HIGH'::segment_code),
  ('CHE', 2011, 0.9, 'HIGH'::segment_code),
  ('TWN', 2011, 0.9, 'HIGH'::segment_code),
  ('TJK', 2011, 0.6, 'NODATA'::segment_code),
  ('TZA', 2011, 0.45, 'LOW'::segment_code),
  ('THA', 2011, 0.6, 'LOW'::segment_code),
  ('TGO', 2011, 0.45, 'NODATA'::segment_code),
  ('TTO', 2011, 0.75, 'NODATA'::segment_code),
  ('TUN', 2011, 0.75, 'HIGH'::segment_code),
  ('TUR', 2011, 0.75, 'HIGH'::segment_code),
  ('UGA', 2011, 0.45, 'LOW'::segment_code),
  ('UKR', 2011, 0.6, 'HIGH'::segment_code),
  ('ARE', 2011, 0.75, 'HIGH'::segment_code),
  ('GBR', 2011, 0.9, 'HIGH'::segment_code),
  ('USA', 2011, 0.9, 'HIGH'::segment_code),
  ('URY', 2011, 0.75, 'HIGH'::segment_code),
  ('UZB', 2011, 0.45, 'LOW'::segment_code),
  ('VEN', 2011, 0.45, 'HIGH'::segment_code),
  ('VNM', 2011, 0.6, 'LOW'::segment_code),
  ('VGB', 2011, 0.9, 'NODATA'::segment_code),
  ('VIR', 2011, 0.9, 'NODATA'::segment_code),
  ('YEM', 2011, 0.45, 'LOW'::segment_code),
  ('ZMB', 2011, 0.6, 'LOW'::segment_code),
  ('ZWE', 2011, 0.45, 'NODATA'::segment_code)
ON CONFLICT (iso3, as_of_year) DO NOTHING;

-- Dev-only tenancy seed. Creates one internal org, one client org, and a system org for service accounts.
-- Users must be created via Studio UI; their memberships are added separately (see Task 8 manual steps).

INSERT INTO organisations (id, name, status) VALUES
  ('00000000-0000-0000-0000-0000000000a1', 'Anchor Point Risk (internal)', 'internal'::organisation_status),
  ('00000000-0000-0000-0000-0000000000b1', 'Sample Client Bank',          'client'::organisation_status),
  ('00000000-0000-0000-0000-0000000000c1', 'System Service Accounts',     'system'::organisation_status)
ON CONFLICT (id) DO NOTHING;

